[package]
name = "shadotask"
version = "0.1.0"
edition = "2021"
authors = ["Shadorain <shadorain7517@gmail.com>"]


[dependencies]
ropey = "1.5.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_repr = "0.1.8"
serde_json = "1.0.81"
clap = { version = "3.0", features = ["derive"] }
